
service: narouz-makar-aws-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnet6
  environment:
    Bucket_Name: sandbox-0101010-${self:service}-assets
    ToDo_External_Url: https://jsonplaceholder.typicode.com
    Access_key_ID: '{{resolve:secretsmanager:narouz_aws_challenge_access_key_id:SecretString:SECRET}}'
    Secret_Access_Key: '{{resolve:secretsmanager:narouz_aws_challenge_secret_access_key:SecretString:SECRET}}'
  apiGateway:
    apiKeys:
      - ${self:service}-first_key
      - ${self:service}-second_key
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*

        Condition:
          IpAddress:
            aws:SourceIp:
              - 208.53.195.66/32
              - 50.202.73.133
              - 192.168.1.17

  s3:
    assetsBucket:
      name: ${self:provider.environment.Bucket_Name}
      accessControl: Private
      bucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
package:
  individually: true

functions:
  LoadTodos:
    handler: AwsDotnetCsharp::AwsDotnetCsharp.Handler::LoadTodos
    events:
    - http:
        path: todos
        method: get
        private: true
    package:
      artifact: bin/Release/net6.0/package.zip


resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.Bucket_Name}
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      DependsOn:
        - LoadTodosLambdaFunction
      Properties:
        Name: ${self:service}
